#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
# Usage: Copy this to your .git/hooks folder
#
NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "PREFIX-$NAME"': '$(cat "$1") > "$1" #
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 